name: Test and Deploy Northeastern Chatbot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements_runpod.txt
        
    - name: Run local tests
      run: |
        python runpod_quick_test.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CHROMA_API_KEY: ${{ secrets.CHROMA_API_KEY }}
        CHROMA_HOST: ${{ secrets.CHROMA_HOST }}
        CHROMA_PORT: ${{ secrets.CHROMA_PORT }}
        
    - name: Build Docker image
      run: |
        docker build --platform linux/amd64 -t northeastern-chatbot:${{ github.sha }} .
        
    - name: Test Docker image
      run: |
        docker run --rm northeastern-chatbot:${{ github.sha }} python -c "print('Docker image test successful')"
        
    - name: Deploy to RunPod (on release)
      if: github.event_name == 'release'
      run: |
        echo "🚀 Ready for RunPod deployment!"
        echo "Image: northeastern-chatbot:${{ github.sha }}"
        echo "Go to https://console.runpod.io/serverless to deploy"
